name: notekeeper
description: A new Flutter application.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.16.1

  cupertino_icons: ^0.1.3
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true